### ISSUE TITLE
[PE-D] Hyperlink to Download Jar File in Quick Start is wrong

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-2/tp#145]
![image.png](https://raw.githubusercontent.com/alvynben/ped/main/files/80d5cc8c-4f7e-4cc6-8fa4-133e757aee3b.png)

This link redirects back to the user guide as the hyperlink attached to the link is: https://ay2122s1-cs2113t-f11-2.github.io/tp/UserGuide.html

-------------
Labels: `severity.High` `type.DocumentationBug`
original: alvynben/ped#1

**Comment by kelvneo** [comment]
Wrong team
