### ISSUE TITLE
[PE-D] Typo in UG Introduction: "Students", not "students"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-2/tp#148]
![image.png](https://raw.githubusercontent.com/alvynben/ped/main/files/1f6beb47-b889-47e9-a5dc-e8a155338f6d.png)

The word student in the last sentence is unnecessarily capitalised.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: alvynben/ped#3

**Comment by kelvneo** [comment]
Related: #54
