### ISSUE TITLE
[PE-D] Add module command bug - Random text not handled after command, allows user to continue adding the module

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-2/tp#149]
![image.png](https://raw.githubusercontent.com/APZH/ped/main/files/69fb6cd6-8dc4-4a66-a4d1-7504dfe3fad7.png)

The command above did not match the format as described in the UG, but still allows a user to add the module without handling the incorrect format with the additional "random_text" string appended behind the command.

![image.png](https://raw.githubusercontent.com/APZH/ped/main/files/77394c53-4e73-4a7a-8872-dd9b4b547a60.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: APZH/ped#1

**Comment by 3m0W33D** [comment]
Fix in #144
