### ISSUE TITLE
[PE-D] Schedule and timetable integration error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-2/tp#151]
![Screenshot 2021-10-29 at 4.50.06 PM.png](https://raw.githubusercontent.com/saravanamani1999/ped/main/files/6f6e4e85-eba8-4787-b06c-e239c07a489a.png)

I added a total of 2 scheduled lessons to `CS1231` > `Schedule`. The first one is `CS2113` (just testing out if the program allows for other module codes) followed by `tutorial 1` but in the timetable only `tutorial 1` is displayed.
When I try to delete the `tutorial 1` lesson which is displayed as index 1 in the timetable, the `CS2113` scheduled lesson does not appear on my timetable but it is able to get deleted from the schedule. Is there an issue with integration between `timetable` and `schedule`?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: saravanamani1999/ped#1

**Comment by 3m0W33D** [comment]
Issue was because of the edits done to json file were not validated.
