### ISSUE TITLE
[PE-D] Grammer mistake in Purpose in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-2/tp#171]
![image.png](https://raw.githubusercontent.com/alvynben/ped/main/files/8854fcb5-08c4-4db4-aac0-2da7076fe2ea.png)

The phrasing is hard to understand due to incorrect grammar in the sentence: "The document will bring you through a detailed guide on all existing commands as well as aiding you in installing TerminNUS."

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: alvynben/ped#6

**Comment by kelvneo** [comment]
Related: #54
