### ISSUE TITLE
[PE-D] Not being able to timings of `schedule`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T10-2/tp#178]
As a user, i think it will be helpful to update timings on the scheduled lessons if there are any new events popping up which causes a change in the timing.
![Screenshot 2021-10-29 at 5.43.06 PM.png](https://raw.githubusercontent.com/saravanamani1999/ped/main/files/1b942c40-98b4-49c7-8e27-cd529025d800.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: saravanamani1999/ped#10

**Comment by kelvneo** [comment]
We have taken note of the feedback, but we will not be implementing the feature for upcoming release.
